using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebGitNet.AspNetImplmentations
{
    public class MyHttpBrowserCapabilities : HttpBrowserCapabilitiesBase
    {
        public MyHttpBrowserCapabilities() : base()
        {
            //_default = new HttpBrowserCapabilities();
        }
        //private readonly HttpBrowserCapabilities _default;

        //public override ArrayList Browsers => _default.Browsers;
        //public override bool ActiveXControls => _default.ActiveXControls;
        //public override bool AOL => _default.AOL;
        //public override bool BackgroundSounds => _default.BackgroundSounds;
        //public override bool Beta => _default.Beta;
        //public override bool CanCombineFormsInDeck => _default.CanCombineFormsInDeck;
        //public override bool CanInitiateVoiceCall => _default.CanInitiateVoiceCall;
        //public override bool CanRenderAfterInputOrSelectElement => _default.CanRenderAfterInputOrSelectElement;
        //public override bool CanRenderEmptySelects => _default.CanRenderEmptySelects;
        //public override bool CanRenderInputAndSelectElementsTogether => _default.CanRenderInputAndSelectElementsTogether;
        //public override bool CanRenderMixedSelects => _default.CanRenderMixedSelects;
        //public override bool CanRenderOneventAndPrevElementsTogether => _default.CanRenderOneventAndPrevElementsTogether;
        //public override bool CanRenderPostBackCards => _default.CanRenderPostBackCards;
        //public override bool CanRenderSetvarZeroWithMultiSelectionList => _default.CanRenderSetvarZeroWithMultiSelectionList;
        //public override bool CanSendMail => _default.CanSendMail;
        //public override bool CDF => _default.CDF;
        //public override bool Cookies => _default.Cookies;
        //public override bool Crawler => _default.Crawler;
        //public override bool Frames => _default.Frames;
        //public override bool HasBackButton => _default.HasBackButton;
        //public override bool HidesRightAlignedMultiselectScrollbars => _default.HidesRightAlignedMultiselectScrollbars;
        //public override bool IsColor => _default.IsColor;
        //public override bool IsMobileDevice => _default.IsMobileDevice;
        //public override bool JavaApplets => _default.JavaApplets;
        //public override bool RendersBreakBeforeWmlSelectAndInput => _default.RendersBreakBeforeWmlSelectAndInput;
        //public override bool RendersBreaksAfterHtmlLists => _default.RendersBreaksAfterHtmlLists;
        //public override bool RendersBreaksAfterWmlAnchor => _default.RendersBreaksAfterWmlAnchor;
        //public override bool RendersBreaksAfterWmlInput => _default.RendersBreaksAfterWmlInput;
        //public override bool RendersWmlDoAcceptsInline => _default.RendersWmlDoAcceptsInline;
        //public override bool RendersWmlSelectsAsMenuCards => _default.RendersWmlSelectsAsMenuCards;
        //public override bool RequiresAttributeColonSubstitution => _default.RequiresAttributeColonSubstitution;
        //public override bool RequiresContentTypeMetaTag => _default.RequiresContentTypeMetaTag;
        //public override bool RequiresControlStateInSession => _default.RequiresControlStateInSession;
        //public override bool RequiresDBCSCharacter => _default.RequiresDBCSCharacter;
        //public override bool RequiresHtmlAdaptiveErrorReporting => _default.RequiresHtmlAdaptiveErrorReporting;
        //public override bool RequiresLeadingPageBreak => _default.RequiresLeadingPageBreak;
        //public override bool RequiresNoBreakInFormatting => _default.RequiresNoBreakInFormatting;
        //public override bool RequiresOutputOptimization => _default.RequiresOutputOptimization;
        //public override bool RequiresPhoneNumbersAsPlainText => _default.RequiresPhoneNumbersAsPlainText;
        //public override bool RequiresSpecialViewStateEncoding => _default.RequiresSpecialViewStateEncoding;
        //public override bool RequiresUniqueFilePathSuffix => _default.RequiresUniqueFilePathSuffix;
        //public override bool RequiresUniqueHtmlCheckboxNames => _default.RequiresUniqueHtmlCheckboxNames;
        //public override bool RequiresUniqueHtmlInputNames => _default.RequiresUniqueHtmlInputNames;
        //public override bool RequiresUrlEncodedPostfieldValues => _default.RequiresUrlEncodedPostfieldValues;
        //public override bool SupportsAccesskeyAttribute => _default.SupportsAccesskeyAttribute;
        //public override bool SupportsBodyColor => _default.SupportsBodyColor;
        //public override bool SupportsBold => _default.SupportsBold;
        //public override bool SupportsCacheControlMetaTag => _default.SupportsCacheControlMetaTag;
        //public override bool SupportsCallback => _default.SupportsCallback;
        //public override bool SupportsCss => _default.SupportsCss;
        //public override bool SupportsDivAlign => _default.SupportsDivAlign;
        //public override bool SupportsDivNoWrap => _default.SupportsDivNoWrap;
        //public override bool SupportsEmptyStringInCookieValue => _default.SupportsEmptyStringInCookieValue;
        //public override bool SupportsFontColor => _default.SupportsFontColor;
        //public override bool SupportsFontName => _default.SupportsFontName;
        //public override bool SupportsFontSize => _default.SupportsFontSize;
        //public override bool SupportsImageSubmit => _default.SupportsImageSubmit;
        //public override bool SupportsIModeSymbols => _default.SupportsIModeSymbols;
        //public override bool SupportsInputIStyle => _default.SupportsInputIStyle;
        //public override bool SupportsInputMode => _default.SupportsInputMode;
        //public override bool SupportsItalic => _default.SupportsItalic;
        //public override bool SupportsJPhoneMultiMediaAttributes => _default.SupportsJPhoneMultiMediaAttributes;
        //public override bool SupportsJPhoneSymbols => _default.SupportsJPhoneSymbols;
        //public override bool SupportsQueryStringInFormAction => _default.SupportsQueryStringInFormAction;
        //public override bool SupportsRedirectWithCookie => _default.SupportsRedirectWithCookie;
        //public override bool SupportsSelectMultiple => _default.SupportsSelectMultiple;
        //public override bool SupportsUncheck => _default.SupportsUncheck;
        //public override bool SupportsXmlHttp => _default.SupportsXmlHttp;
        //public override bool Tables => _default.Tables;
        //public override bool UseOptimizedCacheKey => _default.UseOptimizedCacheKey;
        //public override bool VBScript => _default.VBScript;
        //public override bool Win16 => _default.Win16;
        //public override bool Win32 => _default.Win32;
        //public override double GatewayMinorVersion => _default.GatewayMinorVersion;
        //public override double MinorVersion => _default.MinorVersion;
        //public override IDictionary Adapters => _default.Adapters;
        //public override IDictionary Capabilities => _default.Capabilities;
        //public override int DefaultSubmitButtonLimit => _default.DefaultSubmitButtonLimit;
        //public override int GatewayMajorVersion => _default.GatewayMajorVersion;
        //public override int MajorVersion => _default.MajorVersion;
        //public override int MaximumHrefLength => _default.MaximumHrefLength;
        //public override int MaximumRenderedPageSize => _default.MaximumRenderedPageSize;
        //public override int MaximumSoftkeyLabelLength => _default.MaximumSoftkeyLabelLength;
        //public override int NumberOfSoftkeys => _default.NumberOfSoftkeys;
        //public override int ScreenBitDepth => _default.ScreenBitDepth;
        //public override int ScreenCharactersHeight => _default.ScreenCharactersHeight;
        //public override int ScreenCharactersWidth => _default.ScreenCharactersWidth;
        //public override int ScreenPixelsHeight => _default.ScreenPixelsHeight;
        //public override int ScreenPixelsWidth => _default.ScreenPixelsWidth;
        //public override string Browser => _default.Browser;
        //public override string GatewayVersion => _default.GatewayVersion;
        //public override string HtmlTextWriter => _default.HtmlTextWriter;
        //public override string Id => _default.Id;
        //public override string InputType => _default.InputType;
        //public override string MinorVersionString => _default.MinorVersionString;
        //public override string MobileDeviceManufacturer => _default.MobileDeviceManufacturer;
        //public override string MobileDeviceModel => _default.MobileDeviceModel;
        //public override string Platform => _default.Platform;
        //public override string PreferredImageMime => _default.PreferredImageMime;
        //public override string PreferredRenderingMime => _default.PreferredRenderingMime;
        //public override string PreferredRenderingType => _default.PreferredRenderingType;
        //public override string PreferredRequestEncoding => _default.PreferredRequestEncoding;
        //public override string PreferredResponseEncoding => _default.PreferredResponseEncoding;
        //public override string RequiredMetaTagNameValue => _default.RequiredMetaTagNameValue;
        //public override string this[string key] => _default[key];
        //public override string Type => _default.Type;
        //public override string Version => _default.Version;
        //public override Type TagWriter => _default.TagWriter;
        //public override Version ClrVersion => _default.ClrVersion;
        //public override Version EcmaScriptVersion => _default.EcmaScriptVersion;
        //public override Version JScriptVersion => _default.JScriptVersion;
        //public override Version MSDomVersion => _default.MSDomVersion;
        //public override Version W3CDomVersion => _default.W3CDomVersion;
    }
}